server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice_db?allowPublicKeyRetrieval=true&useSSL=FALSE
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: USER-SERVICE

  zipkin:
    base-url: http://127.0.0.1:9411/
